[package]
name = "argparser"
version = "0.1.0"
authors = ["bailaohe <bailaohe@gmail.com>"]

[dependencies]
clap = "*"

clippy = {version = "*", optional = true}

[features]
default = []
# Add feature "foo" here, then you can use it. 
# Our "foo" feature depends on nothing else.
foo = []
